spring.application.name=TrabajoAvance_Kevin
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/BDAvance
spring.datasource.username=postgres
spring.datasource.password=123456
